[book]
authors = ["Daan van Berkel"]
language = "en"
multilingual = false
src = "src"
title = "PostScript; How to talk to your printer"

[output.html]
mathjax-support = true
additional-css = ["custom.css"]
